# Generated by Django 4.2.13 on 2024-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('chena', models.IntegerField(max_length=10)),
            ],
        ),
    ]
